# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# set working directory
WORKDIR /app

# copy project files
COPY pyproject.toml bilibili.py README.md ./

# install dependencies
RUN pip install --no-cache-dir .

# default command
CMD ["python", "bilibili.py"]
